FROM node:18-alpine

WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN apk add --no-cache libc6-compat && \
    yarn install --frozen-lockfile

COPY . .
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
ARG PORT=80
ENV PORT=${PORT}
RUN echo NODE_ENV=${NODE_ENV} && \
    echo PORT=${PORT} && \ 
    sed -i "s/output/\/\/output/g" next.config.js && \
    NODE_ENV=${NODE_ENV} yarn build

EXPOSE ${PORT}

ENV NEXT_TELEMETRY_DISABLED 1

CMD [ "npm", "start" ]