FROM node:18-alpine as build

WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}
ARG PORT=80
ENV PORT=${PORT}
COPY . .
RUN yarn build
EXPOSE ${PORT}
CMD [ "npm", "start" ]